spring:
    datasource:
        url: jdbc:mysql://localhost:3306/lap_trinh_nhung?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
    port: 8081